### ISSUE TITLE
Permission to use your ideas / code for my own project

### ISSUE THREAD

**Issue by ziontee113** [max397574/colortils.nvim#4]
Hi @max397574. I'm planning to develop a color picker plugin for Neovim and I came across this amazing plugin.

I'd love to implement something like your color picker window, which I've thought about but didn't know how to do it in Neovim. Your plugin has educated me on how to do such beautiful UI.

I'm making this post asking your permission to use the idea / parts of the code that makes up the color picker UI.
Thank you for the amazing work :smiley:

**Comment by max397574** [comment]
I'd prefer if you didn't do so
If you want to do something that this picker doesn't already do I'd be very happy to ask a pull request

I feel like it doesn't make much sense to create a plugin that implements parts of the functionality of a different one
especially if you'd copy the code of the existing one

**Comment by ziontee113** [comment]
Yeah that makes sense. I’ll look for alternatives. Thank you :)

**Comment by ziontee113** [comment]
Yeah that makes sense. I’ll look for alternatives. Thank you :)

**Comment by ziontee113** [comment]
Yes I will. Sorry for that.
